FROM node:16
ARG USER_ID=sonid

RUN groupadd -r author && useradd -r -g author $USER_ID
USER root

RUN mkdir -p /home/$USER_ID
RUN mkdir /home/$USER_ID/.npm-global

ENV NPM_CONFIG_PREFIX=/home/$USER_ID/.npm-global
ENV PATH=/home/$USER_ID/.npm-global/bin:$PATH

RUN npm install yarn --global
RUN mkdir -p /home/$USER_ID/app
WORKDIR /home/$USER_ID/app

COPY --chown=$USER_ID . .
COPY ./api/package.json /app
COPY ./api/tsconfig.json /app

RUN npm cache clean --force
RUN yarn

EXPOSE 3000
ENV PORT 3000

CMD ["yarn", "test"]