FROM node:16
ARG USER_ID=sonid

USER $USER_ID

RUN mkdir ~/.npm-global
RUN useradd sonid
RUN npm config set prefix '~/.npm-global'
ENV PATH=/home/$USER_ID/.npm-global/bin:$PATH

RUN npm install yarn --global
RUN mkdir -p /home/$USER_ID/app
WORKDIR /home/$USER_ID/app

COPY --chown=$USER_ID . .
COPY ./api/package.json /app
COPY ./api/tsconfig.json /app

RUN yarn

EXPOSE 3000
ENV PORT 3000

CMD ["yarn", "test"]