version: "3"
services:
  mysql:
    image: mysql:latest
    volumes:
      - ./mainpage-mysql-data:/var/lib/mysql
      - ./mainpage:/docker-entrypoint-initdb.d
    environment:
      LC_ALL: C.UTF-8
      character-set-server: utf8
      collation-server: utf8_general_ci
      default-character-set: utf8
      default-collation: utf8_general_ci
      innodb-flush-log-at-trx-commit: 0
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: "1234"
    expose:
      - 3306
    ports:
      - "3673:3306"

  # phptool:
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   #links:
  #   #  - mysql
  #   environment:
  #     # - PMA_ARBITRARY=1
  #     - PMA_HOST=mainpage-mysql-1
  #     - PMA_PORT=3306
  #     - PMA_USER=root
  #     - PMA_PASSWORD=1234
  #   ports:
  #     - 3672:80

  api:
    build:
      context: ./
      dockerfile: ./api/dockerFile
    #working_dir: /home/node/app
    volumes:
      - /etc/letsencrypt/live/lsw.kr/privkey.pem:/app/certicates/privkey.pem
      - /etc/letsencrypt/live/lsw.kr/cert.pem:/app/certicates/cert.pem
      - /etc/letsencrypt/live/lsw.kr/chain.pem:/app/certicates/chain.pem
      - ./api/src:/app/src
      - ./api/public:/app/public

    command: "npm test"
    environment:
      NODE_ENV: "production"
      production: "docker"
      KEY_URL: "/etc/letsencrypt/live/lsw.kr"
    ports:
      - "80:8000"
      - "443:443"
      - "3000:3000"
# 외부 통신 허용 설정
# networks:
#   out-net:
#     driver: bridge
#     external: true
