version: "3"
services:

  api:
    build:
      context: ./
      dockerfile: ./api/dockerFile
    volumes:
      - ./api/src:/app/src
      - ./api/public:/app/public
      # - /etc/letsencrypt/live/lsw.kr/privkey.pem:/app/certicates/privkey.pem
      # - /etc/letsencrypt/live/lsw.kr/cert.pem:/app/certicates/cert.pem
      # - /etc/letsencrypt/live/lsw.kr/chain.pem:/app/certicates/chain.pem
    command: "npm test"
    environment:
      NODE_ENV: "production"
      production: "docker"
    restart: always
    ports:
      - "80:8000"
      

  mysql:
    restart: always
    image: mysql:latest
    volumes:
      - ./mainpage-mysql-data:/var/lib/mysql
      - ./mainpage:/docker-entrypoint-initdb.d
    environment:
      LC_ALL: C.UTF-8
      character-set-server: utf8
      collation-server: utf8_general_ci
      default-character-set: utf8
      default-collation: utf8_general_ci
      innodb-flush-log-at-trx-commit: 0
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: "1234"
    expose:
      - 3306
    ports:
      - "3673:3306"

